export const allCities = [
  "Abu Dhabi", "Abidjan", "Accra", "Addis Ababa", "Adelaide", "Algiers", "Almaty", "Amman", "Amsterdam", "Ankara", "Antananarivo", "Antwerp", "Ashgabat", "Astana", "Asuncion", "Athens", "Atlanta", "Auckland", 
  "Baghdad", "Baku", "Bamako", "Bangkok", "Barcelona", "Barranquilla", "Basra", "Beijing", "Beirut", "Belgrade", "Belo Horizonte", "Bengaluru", "Berlin", "Bern", "Birmingham", "Bishkek", "Bogota", "Bordeaux", "Boston", "Brasilia", "Bratislava", "Brazzaville", "Brisbane", "Brussels", "Bucharest", "Budapest", "Buenos Aires", "Busan", 
  "Cairo", "Calgary", "Cali", "Cape Town", "Caracas", "Casablanca", "Chennai", "Chengdu", "Chicago", "Chisinau", "Chongqing", "Cologne", "Colombo", "Conakry", "Copenhagen", "Curitiba", 
  "Dakar", "Dallas", "Damascus", "Dar es Salaam", "Delhi", "Denver", "Dhaka", "Doha", "Dubai", "Dublin", "Durban", "Dusseldorf", 
  "Edinburgh", "Edmonton", "Eindhoven", 
  "Frankfurt", "Fukuoka", 
  "Gaza", "Geneva", "George Town", "Glasgow", "Guadalajara", "Guangzhou", "Guatemala City", "Guayaquil", 
  "Hamburg", "Hanoi", "Harare", "Havana", "Helsinki", "Ho Chi Minh City", "Hong Kong", "Houston", "Hyderabad", 
  "Incheon", "Isfahan", "Islamabad", "Istanbul", "Izmir", 
  "Jakarta", "Jeddah", "Jerusalem", "Johannesburg", 
  "Kabul", "Kampala", "Kano", "Kanpur", "Karachi", "Kathmandu", "Kharkiv", "Khartoum", "Kyiv", "Kigali", "Kingston", "Kinshasa", "Kolkata", "Kuala Lumpur", "Kuwait City", 
  "Lagos", "Lahore", "La Paz", "Las Vegas", "Leipzig", "Lima", "Lisbon", "Liverpool", "Ljubljana", "London", "Los Angeles", "Luanda", "Lyon", 
  "Macau", "Madinah", "Madrid", "Makhachkala", "Malaga", "Male", "Manama", "Manaus", "Manila", "Mannheim", "Maputo", "Marseille", "Mashhad", "Mbabane", "Medan", "Medellin", "Melbourne", "Memphis", "Mexico City", "Miami", "Milan", "Minsk", "Mogadishu", "Monterrey", "Montevideo", "Montreal", "Mumbai", "Munich", "Muscat", 
  "Nagoya", "Nairobi", "Naples", "Nashville", "N'Djamena", "New Delhi", "New York", "Nice", "Nicosia", "Niamey", "Novosibirsk", 
  "Odesa", "Oklahoma City", "Oman", "Omsk", "Osaka", "Oslo", "Ottawa", 
  "Panama City", "Paris", "Patna", "Perth", "Philadelphia", "Phnom Penh", "Phoenix", "Podgorica", "Porto", "Porto Alegre", "Prague", "Pyongyang", 
  "Quebec City", "Quito", 
  "Rabat", "Rawalpindi", "Recife", "Reykjavik", "Riga", "Rio de Janeiro", "Riyadh", "Rome", "Rosario", "Rotterdam", 
  "Saint Petersburg", "Salvador", "Sana'a", "San Antonio", "San Diego", "San Francisco", "San Jose", "Santiago", "Santo Domingo", "Sao Paulo", "Sarajevo", "Seattle", "Seoul", "Seville", "Shanghai", "Sharjah", "Shenzhen", "Singapore", "Skopje", "Sofia", "Stockholm", "Stuttgart", "Surat", "Sydney", 
  "Taipei", "Tallinn", "Tashkent", "Tbilisi", "Tegucigalpa", "Tehran", "Tel Aviv", "The Hague", "Thessaloniki", "Tianjin", "Tijuana", "Tirana", "Tokyo", "Toronto", "Tripoli", "Tunis", "Turin", 
  "Ulaanbaatar", "Utrecht", 
  "Valencia", "Valletta", "Vancouver", "Venice", "Vienna", "Vientiane", "Vilnius", 
  "Warsaw", "Washington D.C.", "Wellington", "Winnipeg", "Wuhan", 
  "Xi'an", "Xiamen", 
  "Yaounde", "Yekaterinburg", "Yerevan", "Yokohama", 
  "Zagreb", "Zaragoza", "Zurich"
];